# id: 1
server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
apuesta:
  nombre: "Pablo"
  apellido: "Berrotaran"
  documento: 39242646
  nacimiento: "1995-08-23"
  numero: 1000
batch:
  max-items: 81